---
- name: Deploy Lightweight VM on Proxmox
  hosts: pve.robinson-home.net
  gather_facts: true
  become: true

  tasks:
    - name: Create Proxmox VM
      proxmox_kvm_vm:
        node: "pve1"
        name: "lightweight-vm"
        ostemplate: "local:kubuntu-23.10-desktop-amd64.iso 
        memory: 512
        onboot: true
        cores: 1
        netif: 'virtio-net,bridge=vmbr0'
        password: "Granby1400!!"
        state: started
      delegate_to: localhost
