- name: Deploy Lightweight VM on Proxmox
  hosts: pve.robinson-home.net
  gather_facts: true
  become: true

  tasks:
    - name: Create Proxmox VM
      community.general.proxmox_kvm:
        node: "pve1"
        name: "lightweight-vm"
        ostemplate: "local:vztmpl/debian-10.0-standard_10.0-1_amd64.tar.gz"
        memory: 512
        onboot: true
        cores: 1
        netif: 'virtio-net,bridge=vmbr0'
        password: "Granby1400!!"
        state: started
      delegate_to: localhost
