- name: Deploy Lightweight VM on Proxmox
  hosts: pve.robinson-home.net
  gather_facts: false
  become: true
  tasks:
    - name: Activate Virtual Environment
      command: "/path/to/your/virtualenv/bin/activate"
      args:
        executable: /bin/bash

    - name: Create Proxmox VM
      community.general.proxmox_kvm:
        api_host: "https://pve.robinson-home.net:8006/api2/json"
        api_user: "root@pam"
        api_password: "Granby1400!!"
        node: "pve1"
        name: "lightweight-vm"
        memory: 512
        onboot: true
        cores: 1
        state: started
