- name: Deploy Lightweight VM on Proxmox
  hosts: localhost
  gather_facts: false
  become: false

  tasks:
    - name: Create Proxmox VM
      community.general.proxmox_kvm:
        api_host: "https://pve.robinson-home.net:8006/api2/json"
        api_user: "your_proxmox_username@pam"
        api_password: "your_proxmox_password"
        node: "pve1"
        name: "lightweight-vm"
        template: "local:vztmpl/debian-10.0-standard_10.0-1_amd64.tar.gz"
        memory: 512
        onboot: true
        cores: 1
        virtio: true  # Use virtio for network interface
        state: started
