- name: Deploy Lightweight VM on Proxmox
  hosts: localhost
  gather_facts: false
  become: false

  tasks:
    - name: Create Proxmox VM
      community.general.proxmox_kvm:
        api_host: "https://pve.robinson-home.net:8006/api2/json"
        api_user: "root@pam"
        api_password: "Granby1400!!"
        node: "pve1"
        name: "lightweight-vm"
        ostemplate: "local:vztmpl/debian-10.0-standard_10.0-1_amd64.tar.gz"
        memory: 512
        onboot: true
        cores: 1
        netif: 'virtio-net,bridge=vmbr0'
        password: "Granby1400!!"
        state: started
