- name: Deploy Lightweight VM on Proxmox
  hosts: localhost
  gather_facts: false
  vars:
    ansible_python_interpreter: /root/.venv/bin/python3
  become: false

  tasks:
    - name: Create Proxmox VM
      community.general.proxmox_kvm:
        api_host: "https://pve.robinson-home.net:8006/api2/json"
        api_user: "your_proxmox_username@pam"
        api_password: "your_proxmox_password"
        node: "pve1"
        name: "lightweight-vm"
        memory: 512
        onboot: true
        cores: 1
        state: started
